apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: secondary-producer-scaler
  namespace: ${keda_namespace}
spec:
  scaleTargetRef:
    kind: Deployment
    name: secondary-producer
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: configmap
    metadata:
      name: ${failover_configmap}
      namespace: ${client_namespace}
      key: secondary-producer-replicas

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: secondary-consumer-scaler
  namespace: ${keda_namespace}
spec:
  scaleTargetRef:
    kind: Deployment
    name: secondary-consumer
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: configmap
    metadata:
      name: ${failover_configmap}
      namespace: ${client_namespace}
      key: secondary-consumer-replicas
---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: primary-producer-scaler
  namespace: ${keda_namespace}
spec:
  scaleTargetRef:
    kind: Deployment
    name: primary-producer
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: configmap
    metadata:
      name: ${failover_configmap}
      namespace: ${client_namespace}
      key: primary-producer-replicas

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: primary-consumer-scaler
  namespace: ${keda_namespace}
spec:
  scaleTargetRef:
    kind: Deployment
    name: primary-consumer
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: configmap
    metadata:
      name: ${failover_configmap}
      namespace: ${client_namespace}
      key: primary-consumer-replicas