apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: "${node_pool_role_arn}"
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - system:masters
      - eks-console-dashboard-full-access-group
      - system:discovery
      - system:nodes
      userarn: "${current_aws_user_arn}"
      username: "${current_aws_username}"

