{
 "title": "Kafka Cluster Dashboard",
 "panels": [
  {
   "title": "Number of Cluster Links",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "confluent_kafka_server_cluster_link_count",
     "legendFormat": "{{link_name}} - {{link_state}} - {{mode}}"
    }
   ]
  },
  {
   "title": "Unavailable Cluster Links",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "confluent_kafka_server_cluster_link_count{link_state='unavailable'}",
     "legendFormat": "{{link_name}} - {{mode}}"
    }
   ]
  },
  {
   "title": "Number of Mirror Topics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "confluent_kafka_server_cluster_link_mirror_topic_count",
     "legendFormat": "{{link_name}} - {{link_mirror_topic_state}}"
    }
   ]
  },
  {
   "title": "Active Mirror Topics",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "confluent_kafka_server_cluster_link_mirror_topic_count{link_mirror_topic_state='Mirror'}",
     "legendFormat": "{{link_name}}"
    }
   ]
  },
  {
   "title": "Cluster Link Task States",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "confluent_kafka_server_cluster_link_task_count",
     "legendFormat": "{{link_name}} - {{link_task_name}} - {{link_task_state}} - {{link_task_reason}}"
    }
   ]
  },
  {
   "title": "Mirror Topic State Transition Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "confluent_kafka_server_cluster_link_mirror_transition_in_error",
     "legendFormat": "{{link_name}} - {{link_mirror_topic_state}}"
    }
   ]
  },
  {
   "title": "Destination Mirroring Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "confluent_kafka_server_cluster_link_destination_response_bytes"
    }
   ]
  },
  {
   "title": "Source Mirroring Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "confluent_kafka_server_cluster_link_source_response_bytes"
    }
   ]
  },
  {
   "title": "Mirror Topics Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "confluent_kafka_server_cluster_link_mirror_topic_bytes",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Mirroring Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "confluent_kafka_server_cluster_link_mirror_topic_offset_lag",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}